In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [3]:
df = pd.read_excel("rank_prim.xlsx")

In [4]:
df.head()

,Nombre,Identificador,Tipo,Latitud,Longitud,Biblioteca,Laboratorio / taller,Aula de informática,Aula de música,Comedor,...,Becas,Excursiones_Convivencias,Enfermeria,Huerto,PatioInfantil,CentroTecnologico,GoogleClassroom,Teams,HerramientasPropiasTecnologicas,NecesidadesEspecialesAlumnos
0,"CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA...",46011511,Privado,39464099,-0.345138,1,1,1,1,1,...,0,1,0,1,1,1,1,1,0,1
1,COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MIQ...,46020340,Público,39467756,-0.346745,1,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JAU...,46012616,Público,39465793,-0.341799,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ANT...,46016051,Público,39468286,-0.345694,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,COLEGIO DE EDUCACIÓN PRIMARIA - AIORA,46023882,Público,3946692,-0.338924,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# Obtener el primer valor de cada columna
primeros_valores_por_columna = df.iloc[0]

# Comprobar si todos los valores en cada columna son iguales al primer valor
columnas_con_datos_unicos = df.columns[df.eq(primeros_valores_por_columna).all()]

df = df.drop(columns=columnas_con_datos_unicos)

Todos los colegios tienen el mismo valor en 'Comedor': '1'  
Todos los colegios tienen el mismo valor en 'Webcam': '0'  
Todos los colegios tienen el mismo valor en 'Internado mixto': '0'  
Todos los colegios tienen el mismo valor en 'Internado especial': '0'  
Todos los colegios tienen el mismo valor en 'Internado femenino': '0'  
Todos los colegios tienen el mismo valor en 'Internado masculino': '0'  
Todos los colegios tienen el mismo valor en 'Chino': '0'  
Todos los colegios tienen el mismo valor en 'Italiano': '0'  
Todos los colegios tienen el mismo valor en 'Portugués': '0'  
Todos los colegios tienen el mismo valor en 'Árabe': '0'  
Todos los colegios tienen el mismo valor en 'Japonés': '0'  
Todos los colegios tienen el mismo valor en 'Griego': '0'  
Todos los colegios tienen el mismo valor en 'Inglés a distancia': '0'  
Todos los colegios tienen el mismo valor en 'Ruso': '0'  
Todos los colegios tienen el mismo valor en 'Euskera': '0'  
Todos los colegios tienen el mismo valor en 'ADU': '0'  
Todos los colegios tienen el mismo valor en 'EP': '1'  
Todos los colegios tienen el mismo valor en 'PEV': '0'  
Todos los colegios tienen el mismo valor en 'PIP': '0'  
Todos los colegios tienen el mismo valor en 'ZC': '0'  
Todos los colegios tienen el mismo valor en 'PPEV': '0'  
Todos los colegios tienen el mismo valor en 'PPEC': '0'  
Todos los colegios tienen el mismo valor en 'PEPLI': '1'  
Todos los colegios tienen el mismo valor en 'Mixto': 'Mixto'

In [6]:
print(list(df.columns))

['Nombre', 'Identificador', 'Tipo', 'Latitud', 'Longitud', 'Biblioteca', 'Laboratorio / taller', 'Aula de informática', 'Aula de música', 'Instalaciones deportivas', 'Transporte', 'Cafetería', 'Inst + Gimnasio', 'Salón de actos', 'Pilota', 'Cursos de verano', 'Huerto escolar', 'Aula de idiomas', 'Inst + Gimnas + Piscina', 'Piscina', 'Gimnas + Piscina', 'Castellano', 'Valenciano', 'Inglés', 'Francés', 'Alemán', 'EI', 'BACH', 'FP', 'SEC', 'PIL', 'barrio', 'zonas_verdes', 'densidad_poblacion', 'turismos_e', 'paro', 'renta_media', 'riesgo_pobreza', 'index_equi', 'index_soci', 'index_glob', 'index_gl_1', 'bus_count', 'metro_count', 'Direccion', 'NotaReviews', 'NumReviews', 'Religion', 'Precio', 'Horario', 'Futbol', 'Baloncesto', 'Baile', 'Ajedrez', 'Patinaje', 'Guitarra', 'Judo', 'Teatro', 'Manualidades', 'Programacion', 'ComedorCocinapropia', 'ComedorCateringExterno', 'Becas', 'Excursiones_Convivencias', 'Enfermeria', 'Huerto', 'PatioInfantil', 'CentroTecnologico', 'GoogleClassroom', 'Teams', 'HerramientasPropiasTecnologicas', 'NecesidadesEspecialesAlumnos']

In [7]:
# Grupo 1: Infraestructura y recursos
infraestructura_recursos = ['Biblioteca', 'Laboratorio / taller', 'Aula de informática', 'Aula de música', 
                            'Instalaciones deportivas', 'Transporte', 'Cafetería', 'Inst + Gimnasio', 'Salón de actos',
                            'Pilota', 'Cursos de verano', 'Huerto escolar', 'Aula de idiomas', 'Inst + Gimnas + Piscina',
                            'Piscina', 'Gimnas + Piscina']

# Grupo 2: Idiomas
idiomas = ['Castellano', 'Valenciano', 'Inglés', 'Francés', 'Alemán']

# Grupo 3: Niveles educativos ofrecidos
niveles_educativos = ['EI', 'BACH', 'FP', 'SEC']

# Grupo 4: Entorno y ubicación
entorno_ubicacion = ['zonas_verdes', 'densidad_poblacion', 'turismos_e', 'paro', 'renta_media']

# Grupo 5: Acceso y transporte
acceso_transporte = ['bus_count', 'metro_count']

# Grupo 6: Opiniones y reseñas
opiniones_reseñas = ['NotaReviews', 'NumReviews']



# Grupo 7: Actividades extracurriculares
actividades_extracurriculares = ['Futbol', 'Baloncesto', 'Baile', 'Ajedrez', 'Patinaje',
                                 'Guitarra', 'Judo', 'Teatro', 'Manualidades', 'Programacion', 'Becas', 'Excursiones_Convivencias', 'Enfermeria', 
                                 'PatioInfantil', 'CentroTecnologico', 'GoogleClassroom', 'Teams', 'HerramientasPropiasTecnologicas',
                                 'NecesidadesEspecialesAlumnos']
#Grupo 8
extras = ['Precio', 'Horario']

# Creamos un diccionario para almacenar los grupos
grupos_variables = {
    'Infraestructura y recursos': infraestructura_recursos,
    'Idiomas': idiomas,
    'Niveles educativos ofrecidos': niveles_educativos,
    'Entorno y ubicación': entorno_ubicacion,
    'Acceso y transporte': acceso_transporte,
    'Opiniones y reseñas': opiniones_reseñas,
    'Actividades extracurriculares': actividades_extracurriculares,
    'Extras': extras,
}

# Ahora puedes acceder a cada grupo de variables utilizando el nombre del grupo como clave en el diccionario.
# Por ejemplo:
print("Variables del grupo 'Infraestructura y recursos':", grupos_variables['Infraestructura y recursos'])

Variables del grupo 'Infraestructura y recursos': ['Biblioteca', 'Laboratorio / taller', 'Aula de informática', 'Aula de música', 'Instalaciones deportivas', 'Transporte', 'Cafetería', 'Inst + Gimnasio', 'Salón de actos', 'Pilota', 'Cursos de verano', 'Huerto escolar', 'Aula de idiomas', 'Inst + Gimnas + Piscina', 'Piscina', 'Gimnas + Piscina']

### Grupo 1

In [8]:
def calcular_puntuacion_infraestructura_recursos(datos):
    infraestructura_recursos = ['Biblioteca', 'Laboratorio / taller', 'Aula de informática', 'Aula de música', 
                                'Instalaciones deportivas', 'Transporte', 'Cafetería', 'Inst + Gimnasio', 'Salón de actos',
                                'Pilota', 'Cursos de verano', 'Huerto escolar', 'Aula de idiomas', 'Inst + Gimnas + Piscina',
                                'Piscina', 'Gimnas + Piscina']
    variables_con_peso_mayor = ['Transporte', 'Pilota', 'Cursos de verano', 'Huerto escolar',
                                'Inst + Gimnas + Piscina', 'Piscina', 'Gimnas + Piscina']
    total_variables = len(infraestructura_recursos)
    suma_variables = sum(datos[var] * (2 if var in variables_con_peso_mayor else 1) for var in infraestructura_recursos)
    puntaje_grupo = suma_variables / total_variables
    return puntaje_grupo

# Calcular el puntaje del grupo 1 para cada fila del DataFrame y agregarlo como una nueva columna
df['Recursos'] = df.apply(calcular_puntuacion_infraestructura_recursos, axis=1)

### Grupo 2

In [9]:
def calcular_puntuacion_idiomas(datos):
    # Variables del grupo 2: Idiomas
    idiomas = ['Castellano', 'Valenciano', 'Inglés', 'Francés', 'Alemán']
    
    # Calcular la puntuación del grupo
    total_idiomas = len(idiomas)
    suma_idiomas = sum(datos[idioma] for idioma in idiomas)
    puntaje_grupo = suma_idiomas / total_idiomas
    
    return puntaje_grupo

# Calcular el puntaje del grupo 2 para cada fila del DataFrame y agregarlo como una nueva columna
df['idiomas'] = df.apply(calcular_puntuacion_idiomas, axis=1)

### Grupo 3

In [10]:
def calcular_puntuacion_nivel_educativo(datos):
    # Variables del grupo 3: Niveles educativos ofrecidos
    niveles_educativos = ['EI', 'BACH', 'FP', 'SEC']
    
    # Calcular la puntuación del grupo
    total_niveles = len(niveles_educativos)
    suma_niveles = sum(datos[nivel] for nivel in niveles_educativos)
    puntaje_grupo = suma_niveles / total_niveles
    
    return puntaje_grupo

# Calcular el puntaje del grupo 3 para cada fila del DataFrame y agregarlo como una nueva columna
df['nivel_educativo'] = df.apply(calcular_puntuacion_nivel_educativo, axis=1)

### Grupo 4

In [11]:
def calcular_puntuacion_entorno_ubicacion(datos):
    # Variables del grupo 4: Entorno y ubicación
    entorno_ubicacion = ['zonas_verdes', 'densidad_poblacion', 'turismos_e', 'paro', 'renta_media']
    
    # Seleccionar los datos relevantes
    datos_entorno = datos[entorno_ubicacion]
    
    # Redimensionar los datos a 2D si es necesario
    if len(datos_entorno.shape) == 1:
        datos_entorno = datos_entorno.values.reshape(-1, 1)
    
    # Normalizar los datos
    scaler = MinMaxScaler()
    datos_entorno_normalizados = scaler.fit_transform(datos_entorno)
    
    # Calcular la puntuación del grupo
    puntaje_grupo = datos_entorno_normalizados.mean()
    
    return puntaje_grupo

# Calcular el puntaje del grupo 4 para cada fila del DataFrame y agregarlo como una nueva columna
df['entorno_ubicacion'] = df.apply(calcular_puntuacion_entorno_ubicacion, axis=1)

### Grupo 5

In [12]:
def calcular_puntuacion_acceso_transporte(datos):
    # Variables del grupo 5: Acceso y transporte
    acceso_transporte = ['bus_count', 'metro_count']
    
    # Calcular la puntuación del grupo
    puntaje_grupo = datos[acceso_transporte].mean()
    
    return puntaje_grupo

# Calcular el puntaje del grupo 5 para cada fila del DataFrame y agregarlo como una nueva columna
df['acceso_transporte'] = df.apply(calcular_puntuacion_acceso_transporte, axis=1)

df['acceso_transporte'] = df['acceso_transporte'].div(df['acceso_transporte'].max())

### Grupo 6

In [13]:
def calcular_puntuacion_opiniones_reseñas(datos):
    # Variables del grupo 6: Opiniones y reseñas
    nota_reviews = datos['NotaReviews']
    num_reviews = pd.Series(datos['NumReviews'])
    num_reviews_max = num_reviews.max()

    
    nota_reviews_normalizada = (nota_reviews - 1) / 4  # Normaliza la nota de 1-5 a 0-1
    num_reviews_normalizado = num_reviews / num_reviews_max
    # Calcula la puntuación del grupo
    puntaje_grupo = nota_reviews_normalizada * 0.7 + num_reviews_normalizado * 0.3
    
    return puntaje_grupo

# Calcular el puntaje del grupo 6 para cada fila del DataFrame y agregarlo como una nueva columna
df['opiniones_reseñas'] = df.apply(calcular_puntuacion_opiniones_reseñas, axis=1)

### Grupo 7

In [14]:
def calcular_puntuacion_actividades_extracurriculares(datos):
    # Variables del grupo 7: Actividades extracurriculares
    actividades_extracurriculares = datos[['Futbol', 'Baloncesto', 'Baile', 'Ajedrez', 'Patinaje',
                                 'Guitarra', 'Judo', 'Teatro', 'Manualidades', 'Programacion', 'Becas', 'Excursiones_Convivencias', 'Enfermeria', 
                                 'PatioInfantil', 'CentroTecnologico', 'GoogleClassroom', 'Teams', 'HerramientasPropiasTecnologicas',
                                 'NecesidadesEspecialesAlumnos']]
    
    # Calcular la puntuación del grupo
    puntaje_grupo = actividades_extracurriculares.sum() / len(actividades_extracurriculares)
    
    return puntaje_grupo

# Calcular el puntaje del grupo 7 para cada fila del DataFrame y agregarlo como una nueva columna
df['actividades_extracurriculares'] = df.apply(calcular_puntuacion_actividades_extracurriculares, axis=1)

### Grupo 8

In [15]:
precio = df['Precio'].astype(str)
horario = df['Horario'].astype(str)

In [16]:
def calcular_puntuacion_precio_horario(datos):
    # Variables del grupo 8: Precio y horario
    precio = datos['Precio']
    horario = datos['Horario']
    
    # Inicializar la puntuación
    puntaje_grupo = 0
    
    # Asignar puntajes según las condiciones
    if (precio == "Gratuito o <100€" and horario == "Horario ampliado de mañana y tarde"):
        puntaje_grupo = 1
    elif (precio == "Gratuito o <100€" or horario == "Horario ampliado de mañana y tarde"):
        puntaje_grupo = 0.5
    
    return puntaje_grupo

# Calcular el puntaje del grupo 8 para cada fila del DataFrame y agregarlo como una nueva columna
df['precio_horario'] = df.apply(calcular_puntuacion_precio_horario, axis=1)

In [17]:
df.columns

Index(['Nombre', 'Identificador', 'Tipo', 'Latitud', 'Longitud', 'Biblioteca',
       'Laboratorio / taller', 'Aula de informática', 'Aula de música',
       'Instalaciones deportivas', 'Transporte', 'Cafetería',
       'Inst + Gimnasio', 'Salón de actos', 'Pilota', 'Cursos de verano',
       'Huerto escolar', 'Aula de idiomas', 'Inst + Gimnas + Piscina',
       'Piscina', 'Gimnas + Piscina', 'Castellano', 'Valenciano', 'Inglés',
       'Francés', 'Alemán', 'EI', 'BACH', 'FP', 'SEC', 'PIL', 'barrio',
       'zonas_verdes', 'densidad_poblacion', 'turismos_e', 'paro',
       'renta_media', 'riesgo_pobreza', 'index_equi', 'index_soci',
       'index_glob', 'index_gl_1', 'bus_count', 'metro_count', 'Direccion',
       'NotaReviews', 'NumReviews', 'Religion', 'Precio', 'Horario', 'Futbol',
       'Baloncesto', 'Baile', 'Ajedrez', 'Patinaje', 'Guitarra', 'Judo',
       'Teatro', 'Manualidades', 'Programacion', 'ComedorCocinapropia',
       'ComedorCateringExterno', 'Becas', 'Excursiones_Convivencias',
       'Enfermeria', 'Huerto', 'PatioInfantil', 'CentroTecnologico',
       'GoogleClassroom', 'Teams', 'HerramientasPropiasTecnologicas',
       'NecesidadesEspecialesAlumnos', 'Recursos', 'idiomas',
       'nivel_educativo', 'entorno_ubicacion', 'acceso_transporte',
       'opiniones_reseñas', 'actividades_extracurriculares', 'precio_horario'],
      dtype='object')

In [18]:
def calcular_nota_total(datos):
    # Pesos para cada grupo
    pesos_grupos = {
        'Recursos': 0.3,
        'idiomas': 0.15,
        'nivel_educativo': 0.05,
        'entorno_ubicacion': 0.2,
        'acceso_transporte': 0.1,
        'opiniones_reseñas': 0.05,
        'actividades_extracurriculares': 0.1,
        'precio_horario': 0.05
    }
    
    # Calcular la nota total
    nota_total = sum(datos[group] * peso for group, peso in pesos_grupos.items())
    
    # Escalar la nota total de 0 a 10
    nota_total_escalada = nota_total * 10
    
    return nota_total_escalada 

df['nota_total'] = df.apply(calcular_nota_total, axis=1)
df_ordenado = df.sort_values(by='nota_total')

print(df_ordenado['Nombre'])

90     COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ALE...
95     COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MAX...
52     COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - RAF...
67     COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JOS...
87     COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - TOM...
                             ...
53     CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA...
51     CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA...
21     CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA...
103    CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA...
41     CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA...
Name: Nombre, Length: 116, dtype: object

In [19]:
# Seleccionar las columnas deseadas
columnas_seleccionadas = ['Recursos', 'idiomas', 'nivel_educativo', 'entorno_ubicacion', 
                          'acceso_transporte', 'opiniones_reseñas', 'actividades_extracurriculares', 
                          'precio_horario', 'nota_total']

# Crear un nuevo DataFrame con las columnas seleccionadas
nuevo_df = df[columnas_seleccionadas].copy()
nuevo_df

,Recursos,idiomas,nivel_educativo,entorno_ubicacion,acceso_transporte,opiniones_reseñas,actividades_extracurriculares,precio_horario,nota_total
0,0.3750,0.6,0.75,0.203623,0.217391,0.9300,0.631579,0.5,4.371217
1,0.2500,0.4,0.25,0.203623,0.217391,0.7375,0.000000,0.5,2.718388
2,0.2500,0.4,0.25,0.203623,0.217391,0.8775,0.000000,1.0,3.038388
3,0.3125,0.4,0.25,0.203623,0.217391,0.9650,0.000000,1.0,3.269638
4,0.3750,0.2,0.00,0.203623,0.217391,0.8600,0.000000,1.0,2.979638
...,...,...,...,...,...,...,...,...,...
111,0.2500,0.4,0.25,0.210564,0.260870,0.8950,0.000000,1.0,3.104497
112,0.5000,0.4,0.75,0.223016,0.260870,0.8075,0.947368,1.0,5.033019
113,0.2500,0.4,0.25,0.223016,0.260870,0.9125,0.052632,1.0,3.190782
114,0.2500,0.2,0.25,0.223016,0.260870,0.8600,0.000000,1.0,2.811901
115,0.1875,0.4,0.25,0.207431,0.304348,0.9300,0.000000,1.0,2.971709

In [22]:
rank = df[['Nombre', 'nota_total']]

# Ordenar el nuevo DataFrame por la columna 'puntuacion_final' de mayor a menor
rank = rank.sort_values(by='nota_total', ascending=False)

# Mostrar el nuevo DataFrame ordenado
for i in rank["Nombre"]:
    print(i)
    
rank.to_excel("Ranking_Primaria.xlsx", index = False)

CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SALESIANOS-SAN JUAN BOSCO
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - PUREZA DE MARÍA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - PUREZA DE MARÍA GRAO
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SAGRADO CORAZÓN HH. MARISTAS
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - ESCUELAS PÍAS-MALVARROSA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SANTA ANA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - HOGAR NUESTRA SEÑORA DEL ROSARIO
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - PÍO XII
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SAN JOSÉ DE CALASANZ
CENTRO PRIVADO DE EDUCACIÓN PRIMARIA Y SECUNDARIA - SANTO TOMÁS DE VILLANUEVA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - ACADEMIA JARDÍN
CENTRO PRIVADO DE EDUCACIÓN INFANTIL Y PRIMARIA - MARTÍ SOROLLA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - ESCUELAS PÍAS
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - ARGOS
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SAGRADA FAMILIA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - COMENIUS CENTRE EDUCATIU
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - CHINER VILLARROYA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - LA ANUNCIACIÓN
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - ESCLAVAS DE MARÍA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - JESÚS MARÍA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PROFESSOR RAMIRO JOVER
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SANTA MARÍA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - NUESTRA SEÑORA DE LORETO
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - ESCOLÀPIES VALÈNCIA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SANTIAGO APÓSTOL
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - JESÚS MARÍA-FUENSANTA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SAN PEDRO PASCUAL
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - SAN MARCELINO
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - MANTELLATE
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - FERNANDO DE LOS RIOS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - BENIMACLET
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - LLUÍS GUARNER
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - LA FONTETA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - NUESTRA SEÑORA DEL PILAR
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - LES ARENES
CENTRO PRIVADO DE EDUCACIÓN INFANTIL Y PRIMARIA - MARJO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PROFESOR BARTOLOMÉ COSSIO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - VICENTE BLASCO IBÁÑEZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - L'ALBEREDA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CAVITE-ISLA DE HIERRO
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - MARÍA INMACULADA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CARLES SALVADOR
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - EL AVE MARÍA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SALVADOR TUSET
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PARE CATALÀ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CAMPANAR
CENTRO PRIVADO DE EDUCACIÓN PRIMARIA Y SECUNDARIA - CONCHA ESPINA II
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JAIME BALMES
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SECTOR AÉREO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - 9 D'OCTUBRE
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - DOCTOR OLÓRIZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CASTELLAR-OLIVERAL
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - COMUNITAT VALENCIANA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SAN JUAN DE RIBERA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CERVANTES
COLEGIO DE EDUCACIÓN PRIMARIA - PRIMER MARQUÉS DEL TURIA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PABLO NERUDA
CENTRO PRIVADO DE EDUCACIÓN INFANTIL, PRIMARIA Y SECUNDARIA - CLARET FUENSANTA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MESTALLA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JESÚS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - TOMÁS DE VILLARROYA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - 8 DE MARÇ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ANTONIO GARCÍA LÓPEZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - LUIS VIVES
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - TORREFIEL
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - RODRÍGUEZ FORNOS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SARA FERNÁNDEZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - BENIMÀMET
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - IVAF-LUIS FORTICH
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - VIVERS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PROFESOR SANCHIS GUARNER
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - RAFAEL MATEU CÁMARA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - BALLESTER FANDOS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - FEDERICO GARCÍA LORCA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MONTOLIVET
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - VICENTE GAOS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MALVA-ROSA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - FAUSTO MARTÍNEZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - GASPAR GIL POLO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SANT ISIDRE
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - LES ARTS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - EXPLORADOR ANDRÉS
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JUAN MANUEL MONTOYA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JAUME I
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - FORN D'ALCEDO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SERRERÍA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MARE NOSTRUM
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - HUMANISTA MARINER
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - EL GRAU
COLEGIO DE EDUCACIÓN PRIMARIA - AIORA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ANTONIO MACHADO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CIUDAD DE BOLONIA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PINEDO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SAN JOSÉ DE CALASANZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ELISEO VIDAL
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - TEODORO LLORENTE
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SANTO ÁNGEL DE LA GUARDA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ALMUDENA MUÑOZ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ANGELINA CARNICER
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - DOCTOR BARCIA GOYANES
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PROFESOR LUIS BRAILLE
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - L'AMISTAT
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SAN FERNANDO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MIGUEL HERNÁNDEZ
CENTRO PRIVADO DE EDUCACIÓN INFANTIL Y PRIMARIA - MERCERATOR
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - CIUTAT ARTISTA FALLER
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - SAN PEDRO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MIQUEL ADLERT I NOGUEROL
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PROFESOR SANTIAGO GRISOLIA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - NICOLAU PRIMITIU GÓMEZ SERRANO
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - PADRE MANJÓN
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - TOMÁS DE MONTAÑANA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - JOSÉ SOTO MICÓ
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - RAFAEL ALTAMIRA
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - MAX AUB
COLEGIO DE EDUCACIÓN INFANTIL Y PRIMARIA - ALEJANDRA SOLER